### ISSUE TITLE
make transcript writes enabled off be "sticky"

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#124]
Every time I login, I see markedly slow performance with the first browser I try to open.  So I have to wait for it to finish, go back to the transcript, and unset the make transcript writes enabled option.  

I'd like this setting to be remembered or have some way to set it to default to off.

**Comment by ericwinger** [comment]
I've added two ways to do this.  In theory this could be a way to hold client & server post login preferences. 
Client:
- In the Jadeite working directory, add a file called ``Jadeite.prefs`` with contents ``transcriptEnabled false``  That should turn off your transcripts by default. fyi - this is the only command understood in this file right now. 
Server: 
- As part of the work for #132 I added a server post login hook. Commit a block as such then login: 
``UserGlobals at: #JadeitePreferences put: [RowanAnsweringService new turnOffTranscriptWrites]``

In theory, we need to have both client & server post login execution available, so that's why I added both. 

Added in Oscar 3.0.26

**Comment by LisaAlmarode** [comment]
The Jadeite.prefs doesn't work. Verified working directory: is the syntax correct? 

![image](https://user-images.githubusercontent.com/13142166/45001154-a2182980-af7f-11e8-98c7-7341c561089d.png)

The UserGlobals key system does work as expected.

**Comment by ericwinger** [comment]
@LisaAlmarode  It appears that the method in JadeitePreferences was stripped out - a perpetual frustration with Dolphin. But I added a sender to the method and it seemed to stick around in the .exe. Fixed in 3.0.27.
