### ISSUE TITLE
Jadeite debugger - Alphabetical variables

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#314]
It would be nice if the Jadeite debugger would display the temp and inst vars in alphabetical order while simultaneously differentiating between the two.

**Comment by ericwinger** [comment]
Fixed in 3.1.0. 
- receiver first
- sorted  receiver inst vars next
- sorted args & temps last

**Comment by LisaAlmarode** [comment]
- [ ] It doesn't show dynamic instance variables.  In the example below, extraInfo is dynamic.

I'm slightly uncomfortable with alphabetizing the inst vars since I'm used to the order being as per the class def/list of variables.  But this may just be habit.

- [ ] However - it was a problem when I was looking at an inspector on this object and the order was not the same. possibly the inspectors should alphabetize?  One likes to be able to compare easily. 

![image](https://user-images.githubusercontent.com/13142166/78706011-37e60a00-78c3-11ea-979f-7783c0715526.png)

**Comment by dalehenrich** [comment]
I'm concerned about partial alphabetizing ... if we're going to alphabetize, the whole list should be alphabetized otherwise there is no value in alphabetizing ... When I am looking for a specific variable name, I know the name of the variable, but I may not know that it is an inst var, arg, temp var, or??? ... 

AFAICT, this _is_ the use case for alphabetizing ... I spend a fair amount of time scrolling around in the inspector pane looking for the variable I am interested in. If the list is not completely alphabetized, I will continue to have to scroll around in the list of variables looking for the one I am interested in ...

With that said, if there were some visual indication of the different divisions so if I am looking for a var, I can at least see the beginning and end of the alphabetized sections  ... 

For myself, I don't need to have the inspector "tell" me whether a variable is an iv, block temp, or argument ... I know where to look to answer those questions ... so I'm fine with a purely alphabetized list ... but if you do have ordered sections of variables, at least label or otherwise differentiate the sections so I can get the information you are trying to communicate:)

**Comment by ericwinger** [comment]
To make the instance variables stand out from the args and temps, I'm playing around with a layout that creates headers for easier identification. The variables would stay alphabetized within the two groups. If there are no variables within a group, the header is not displayed. Even if one doesn't know if a variable is an arg, temp, or inst var, the headers make it easier to scan.  

Examples below. Thoughts? 

![image](https://user-images.githubusercontent.com/36212516/92285400-0c3e6e80-eeb9-11ea-8c6a-f945e6840371.png)

![image](https://user-images.githubusercontent.com/36212516/92285447-309a4b00-eeb9-11ea-9ff7-b2b61540b877.png)

![image](https://user-images.githubusercontent.com/36212516/92285125-6854c300-eeb8-11ea-9e3a-f0ebbe9611c4.png)

**Comment by dalehenrich** [comment]
I like the headers... separating args from temps might be useful when there are more than 3 or 4 args or more than 5 or 6 temps (or something along those lines)

**Comment by ericwinger** [comment]
Going to call this fixed. We can tweak the display after users have had a chance to play with it.

**Comment by LisaAlmarode** [comment]
Dynamic instance variables displayed, check (in 3.2.9).
The inconsistent alphabetization between the debugger and inspector bothers me, but we'll see how that goes along in actual use, it's not a core issue.
