### ISSUE TITLE
Need rowan support for Behavior>>compileMissingAccessingMethods

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#319]
Behavior>>compileMissingAccessingMethods (or equivalent) will be a handy addition to the Jadeite tool set. It would be nice if it was integrated in Rowan.

**Comment by dalehenrich** [comment]
I think this can be done in Jadeite ... but worth discussing if not clear ...

**Comment by ericwinger** [comment]
@dalehenrich @LisaAlmarode  I can do this in Jadeite. 

However, the method ``Behavior>>compileMissingAccessingMethods`` will still be available. If a user executes this method which is not marked as private, they will create non-rowanized accessor methods. Those methods will throw an error if an attempt is made to modify or delete them. I don't think that's very friendly. 

Seems that regardless of the Jadeite implementation, we should rowanize this method. 

Lack of the feature in Jadeite has been noticed by customer in #382. 

Thoughts?

**Comment by dalehenrich** [comment]
With regards to `Behavior>>compileMissingAccessingMethods` being present in the image, there are a ton of methods that are *dangerous* to use ... at this point in time, we are not going to be changing existing base methods ... right now we should focus on getting Rowan and Jadeite into a usable state so that customers aren't tempted to use *dangerous* methods:) ... So we just need to implement `Behavior>>rwCompileMissingAccessingMethods` in terms of the Rowan tools ... let me know if you need me to be help with the implementation ...

**Comment by LisaAlmarode** [comment]
I agree with Dale, sufficiently determined customers can always make a mess.  Having a Rowan service and Jadeite menu option at least gives us the convenience.

**Comment by ericwinger** [comment]
Awhile back, I added an ``Add Accessors`` menu option on the ``Variables Tab``. Will let @LisaAlmarode review to see if feature is complete.  Closing, presumed complete.

**Comment by LisaAlmarode** [comment]
Verified that you can select all variables in the tab and generate the lot of accessor methods at one time; so I agree this feature request is implemented.
