### ISSUE TITLE
fileOutClass should file out the rowan compilation variants

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Jadeite#324]
Send ``fileOutClass`` to a behavior and the definition produced in the file is the non-rowan variant of ``subclass:...``.  It should be ``rwSubclass:``

Some gemstone base methods of interest are 
```
Behavior>>fileOutClassDefinitionOn: 
Behavior>>fileOutClass
```

There may be other fileOut* methods that need rowanizing as well.

**Comment by dalehenrich** [comment]
when @ericwinger is ready to change Jadeite, we can arrange for Rowan support ... reminder to see GemTalk/Rowan#361

**Comment by LisaAlmarode** [comment]
I don't want Rowan to remove the ability to file out code in GemStone base format.  I am going to want to move code back and forth between Rowan and GemStone.  I would prefer a separate API to file out rowan code be added to Behavior, and (eventually) be able to file in code that is in rowan or in gemstone base fileout formats.

Also see #70 for support for fileout and filein.

**Comment by dalehenrich** [comment]
Agreed, with GemTalk/Rowan#361, there is support (already) for filing out a packages and/or projects in topaz format (is that what you mean by GemStone base format ... or are you thinking of something different). 

The exact implementation for doing all of these things is up for debate (especially now that I am looking toward v2.0.0) ... but since this a Jadeite issue this discussion will revolve around how should the fileout menus be implemented ... 

Also keep in mind that in 3.5.0, topaz can input tonel files:)

At the moment GemTalk/Rowan#361 (i.e., v2.0.0) is the gating factor

**Comment by LisaAlmarode** [comment]
Well, not exactly input; in 3.5 topaz can accept pasted in tonel format methods using the tmethod command.  However, after some detection I tracked down the secret which is to execute code such as:

CodeLibrarian new
  user: 'DataCurator';
  symbolDictName: 'UserGlobals' ;
  repository: 'tonel:/benton1/users/gsadmin/GS643215/myrowan/Sales/rowan/src/';
  load: #('Customers').

**Comment by dalehenrich** [comment]
so tmethod can't be included in an input script?

**Comment by LisaAlmarode** [comment]
tmethod does work in scripts, but it doesn't help with the input problem, since rowan's tonel files don't include tmethod directives... also, the rowan files have class definitions and topaz can't handle those at all, as far as I know.

**Comment by ericwinger** [comment]
Still waiting for Rowan support. See https://github.com/GemTalk/Jadeite/issues/70#issuecomment-512349705

**Comment by LisaAlmarode** [comment]
closing; this can be handled under more recent issues.
